architecture: "TSMixer"
# Parameters for training model
train_params:
  device: cuda:0
  train_batch_size: 16
  valid_batch_size: 128
  test_batch_size: 128
  max_epochs: 1000
  # Max time used for training (days:hours:mins:secs)
  max_time: "99:00:00:00"
  # Validate after every n epochs
  val_check_interval: 1.0
  num_workers: 20
  gpus: 1
  savefile: "PV-PIML"
  val_batches: 9999999
  train_batches: 1000
  early_stopping:
    strict: false
    verbose: true
    monitor: "val_loss"
    patience: 16
  lr_scheduler:
    name: "ExponentialLR"
    kwargs:
      gamma : 0.99955
  lr: 1e-04
  loss: "mse"
model_params:
  h: 96
  input_size: 480
  n_series: 1
  futr_exog_size: 7
  stat_exog_size: 0
  ghi_zero_mask: true
  activation: "gelu"
dataset:
  path: '/project/p1364-25-2/datasets/pv/processed/nwp_0h'
  previous_days: 5
  continuous: true
  train_fraction: 10000